language: csharp
mono: none
dotnet: 1.0.4
matrix:
  include:
  - os: linux # Ubuntu 14.04
    dist: trusty
    sudo: required      
  - os: osx # OSX 10.11
    osx_image: xcode7.3      
  - os: osx # OSX 10.12
    osx_image: xcode8.1      

# branches to build 
branches:
  only:
  - master

env:
    global: 
    - log_prefix="[$TRAVIS_OS_NAME]"
    - arch=x64
    - configuration="Release"
    - app_output_name="breeze-$arch-$TRAVIS_OS_NAME-Release"
    - api_output_name="api-$arch-$TRAVIS_OS_NAME-Release"
    - os_platform=linux
    - TRAVIS_TAG=cd-unstable

# Work around NuGet issue #2163
# https://github.com/NuGet/Home/issues/2163
# https://github.com/travis-ci/travis-ci/issues/7728
before_install:    
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; $os_platform=darwin; fi

install:
  - nvm install 6
script:
  - chmod +x build.sh
  - ./build.sh

deploy:
  provider: releases
  api_key: 
  - secure: "D9ZTqghn2Ss+G5Lj1YKgd+7+o7BeK4s+mQGwyOiVNCWkb9NAwaFg02zbv4IwI8gc644AAeZGta8LTlCGkYjL1PbAurSxFfrWGTx0+zJDoMeyG6zcd2flHbOt8HMqIkYUgQ8xA4Cw+a5OSYtTKdgYqo3TR2Qqo/2ZueajkSs1qtRtPak5YpHE0WjNKJc4k3vZimWuTGbAAvLIaf9mNRQt9XNhkweNe6iGIpMxIBbfezL0CKBwQtQoRdXELgrCahgwfLbT0ohDXB0tl2LITCcM3SuB+PgjovWWbzFSZseQT75TIjTKASaH6IlGGBt7+c6zcMOLz/k+A86TtuPohwrRtDKdPY9V61NDdY6il67l513Oslp00hFjHUIlO2GZWgWGyUzuxtqTFWP1FhnRXxkYqCIPZnUmajzJcdkwjfm4V9iYn3wETXuhc/J5vKxB41IQoC5g1wpNd89bm719JTuxRGuBrZL1XcXpI6sasnjW3ldA26gmkeZ4ZcFF6HoT4Nie8Jd6Iy72WKatGxdUUHnnqk6GHFJEojmuxxwY9IMTbsJgp95+Q7FMyFFXmXO5lvqiZI/LJy1dV3gK+qhnnigMcsSN5yaIgZvmOTF2vAX8DeeYAnW7f/D37le8HBcoNKhzPwqN1aA6C/Dg27lqYXPgafCaFkXnNO7reW15iBA1Bw8="
  file_glob: true
  file: $TRAVIS_BUILD_DIR/deploy/*.zip
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    branch: master
    tags: true