language: csharp
mono: none
dotnet: 1.0.4
matrix:
  include:
  - os: linux # Ubuntu 14.04
    dist: trusty
    sudo: required      
  - os: osx # OSX 10.11
    osx_image: xcode7.3      
  - os: osx # OSX 10.12
    osx_image: xcode8.1      

# branches to build 
branches:
  only:
  - master

env:
    global: 
    - log_prefix="[$TRAVIS_OS_NAME]"
    - arch=x64
    - configuration="Release"
    - app_output_name="breeze-$arch-$TRAVIS_OS_NAME-Release"
    - api_output_name="api-$arch-$TRAVIS_OS_NAME-Release"
    - os_platform=linux
    - TRAVIS_TAG=cd-unstable

# Work around NuGet issue #2163
# https://github.com/NuGet/Home/issues/2163
# https://github.com/travis-ci/travis-ci/issues/7728
before_install:    
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ulimit -n 1024; $os_platform=darwin; fi

install:
  - nvm install 6
script:
  - chmod +x build.sh
  - ./build.sh

deploy:
  provider: releases
  api_key: 
  - secure: "SefL9ZfsmjSjYyvynK41YdkApTExn5XtHo9lNdM1m+V1TCCFs5KIH/fpSRXaI01boUNi1hEYL2ylLM5+KwAFgBlgGPS0NETdQXg1h291ImuyZrRa1IjVa1DHs7s7XVNm2/TFGH86bpx5Z7VjQk+WbW1GRl5IxJlZiY6dOsshB8lcT2irwu7ZgcLS7gMgsv7EwiNiV90jQufd4wgop15zqdufYcw0IKnMzFuWvDHNalPftmjFcw1Oi1DOE/mTsebKKX4n+R6qbTQPpsHL6sYnad0G2Rv5d+PHrTLarO/p1IvE91Y/DJnMhJytapoqBpKn6WQypE3VGOO0s01JiwCOyHGuB4x+eI8bdp7oqclVQX/azjlhyyY6x7hJKcrLPWe/TnpjFfpFfSY5Z7EhXH+7xbR760ciM1zcDDckcvV20GOIms01ySAglKWr9X/OBl7M7wTR8X0SVHUvvJhS7EzsFORtxNroR4tgaX/4uzO3RWyCOTHBRSh6ChhnefL4Herav19JtZrYQCC5mZRnawGw/9soYSnH8AP4JfLdjic7ubu9tSaVGo0jVuWzb9bjG8RmUKYKHHRnQYa/Iby1VD03bEqLzfe7Ru2bxqk+KiYtZy/aPcMdtntY2BOvBFpTI765npeY1G0OPC3dxO9MvybjwQHrcUEQsUpMY6A7l0j/gXk="
  file_glob: true
  file: $TRAVIS_BUILD_DIR/deploy/*.zip
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    branch: master
    tags: true